get:
  responses:
    default:
      description: "Default response for POST /inbound"
  summary: "POST method for /inbound"
  security:
    - x-amazon-authorizerlambda-apigtw-global: []
  x-amazon-apigateway-integration:
    payloadFormatVersion: "2.0"
    type: "aws_proxy"
    httpMethod: "POST"
    uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:app-inbound-ai-lambda/invocations"
    connectionType: "INTERNET"
post:
  responses:
    default:
      description: "Default response for POST /inbound"
  summary: "POST method for /inbound"
  security:
    - x-amazon-authorizerlambda-apigtw-global: []
  x-amazon-apigateway-integration:
    payloadFormatVersion: "2.0"
    type: "aws_proxy"
    httpMethod: "POST"
    uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:app-inbound-ai-lambda/invocations"
    connectionType: "INTERNET"
  